objects/ApplicationImage__c.object
<CustomObject>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iPadApplication__c</fullName>
        <label>iPad Application</label>
        <referenceTo>iPadApplication__c</referenceTo>
        <relationshipLabel>ApplicationImages</relationshipLabel>
        <relationshipName>ApplicationImages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Application Image</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Application Image Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApplicationImages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/iPadApplication__c.object
<CustomObject>
    <fields>
        <fullName>AboutText__c</fullName>
        <label>About text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>AccountAddress__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountDescription__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Description</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountIndustry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Industry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountPersonBirthdate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Person Birthdate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountPersonName__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Person Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountRating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Rating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountType__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Account Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ApplicationURL__c</fullName>
        <label>Application URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BodyBgImageURL__c</fullName>
        <label>Body Bg Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BodyBgImage__c</fullName>
        <label>Body Bg Image</label>
        <picklist>
            <picklistValues>
                <fullName>white</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>black</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>browse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BodyColor__c</fullName>
        <label>Body Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BodyIsUseImage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Body Is Use Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ChatterId__c</fullName>
        <label>Chatter Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChatterPositionX__c</fullName>
        <defaultValue>130</defaultValue>
        <label>Chatter Position X (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChatterPositionY__c</fullName>
        <defaultValue>20</defaultValue>
        <label>Chatter Position Y (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DashboardId__c</fullName>
        <label>Dashboard Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DashboardPositionX__c</fullName>
        <label>Dashboard Position X (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DashboardPositionY__c</fullName>
        <label>Dashboard Position Y (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FollowUpActivitiesLabel__c</fullName>
        <label>Follow Up Activities Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton1BgColor__c</fullName>
        <label>Follow Up Button 1 Bg Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton1FontColor__c</fullName>
        <label>Follow Up Button 1 Font Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton1Label__c</fullName>
        <label>Follow Up Button 1 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton2BgColor__c</fullName>
        <label>Follow Up Button 2 Bg Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton2FontColor__c</fullName>
        <label>Follow Up Button 2 Font Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpButton2Label__c</fullName>
        <label>Follow Up Button 2 Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpContactImageURL__c</fullName>
        <label>Follow Up Contact Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpContactTwitterHandle__c</fullName>
        <label>Follow Up Contact Twitter Handle</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpInterestLabel__c</fullName>
        <label>Follow Up Interest Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpMapHeight__c</fullName>
        <label>Follow Up Map Height</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FollowUpMapWidth__c</fullName>
        <label>Follow Up Map Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FollowUpMapZoom__c</fullName>
        <defaultValue>15</defaultValue>
        <label>Follow Up Map Zoom</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FollowUpProfileLabel__c</fullName>
        <label>Follow Up Profile Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FollowUpShowEvents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FollowUpShowEvents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FollowUpShowTasks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FollowUpShowTasks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FooterColor__c</fullName>
        <description>Input in Hex (#ffffff)</description>
        <label>Footer Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FooterFontColor__c</fullName>
        <label>Footer Font Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeaderColor__c</fullName>
        <description>Input in hex (#ffffff)</description>
        <label>Header Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeaderFontColor__c</fullName>
        <label>Header Font Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Page_Title__c</fullName>
        <label>Home Page Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginBgImageURL__c</fullName>
        <label>LoginBgImageURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginBgImage__c</fullName>
        <label>LoginBgImage</label>
        <picklist>
            <picklistValues>
                <fullName>white</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>black</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>browse</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LoginBodyColor__c</fullName>
        <label>Login Body Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginButtonColor__c</fullName>
        <label>Login Button Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginButtonLabelColor__c</fullName>
        <label>Login Button Label Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LoginIsUseImage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Login Is Use Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoginLabelColor__c</fullName>
        <label>Login Label Color</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogoURL__c</fullName>
        <label>Logo URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_1_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 1 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_1_Title__c</fullName>
        <label>Page 1 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_2_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 2 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_2_Title__c</fullName>
        <label>Page 2 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_3_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 3 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_3_Title__c</fullName>
        <label>Page 3 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_4_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 4 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_4_Title__c</fullName>
        <label>Page 4 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_5_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 5 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_5_Title__c</fullName>
        <label>Page 5 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_6_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 6 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_6_Title__c</fullName>
        <label>Page 6 Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_7_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 7 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_7_Title__c</fullName>
        <label>Page 7 Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Page_8_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Page 8 Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_8_Title__c</fullName>
        <label>Page 8 Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VisualforcePageLocationX__c</fullName>
        <label>Visualforce Page Location X (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VisualforcePageLocationY__c</fullName>
        <label>Visualforce Page Location Y (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VisualforcePageName__c</fullName>
        <label>Visualforce Page Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>iPad Application</label>
    <nameField>
        <label>iPad Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iPadApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IPadDemoController.cls
public class IPadDemoController {
    public iPadApplication__c iPadAppConfig{get; set;}
    public List<ApplicationImage__c> footerImageList{get; set;}
    public String bgImage{get; set;} 
    public String loginImage{get; set;} 

    public String getLoginPageName(){
        return iPadUtilClass.getLoginPageName();
    }
    public String getHomePageName(){
        return iPadUtilClass.getHomePageName();
    }
    public String getPage1Name(){
        return iPadUtilClass.getPage1Name();
    }
    public String getPage2Name(){
        return iPadUtilClass.getPage2Name();
    }
    public String getPage3Name(){
        return iPadUtilClass.getPage3Name();
    }    
    public String getPage4Name(){
        return iPadUtilClass.getPage4Name();
    }    
    public String getPage5Name(){
        return iPadUtilClass.getPage5Name();
    }    
    public String getPage6Name(){
        return iPadUtilClass.getPage6Name();
    }        
    public String getPage7Name(){
        return iPadUtilClass.getPage7Name();
    }        
    public String getPage8Name(){
        return iPadUtilClass.getPage8Name();
    }        
    public IPadDemoController(){
        List<iPadApplication__c> appList = [select Name, ApplicationURL__c, BodyColor__c, AboutText__c ,
                FooterFontColor__c, HeaderFontColor__c, FooterColor__c, HeaderColor__c, Home_Page_Title__c,
                Page_1_Title__c, Page_2_Title__c, Page_3_Title__c, Page_4_Title__c, 
                Page_5_Title__c, Page_6_Title__c, Page_7_Title__c, Page_8_Title__c,
                LoginButtonColor__c, LoginButtonLabelColor__c, 
                LoginLabelColor__c, LogoURL__c,
                BodyBgImage__c, BodyIsUseImage__c, BodyBgImageURL__c,
                LoginIsUseImage__c, LoginBgImage__c, LoginBgImageURL__c,                
                FollowUpMapHeight__c, FollowUpMapWidth__c, FollowUpMapZoom__c,
                FollowUpShowEvents__c, FollowUpShowTasks__c,
                FollowUpActivitiesLabel__c, FollowUpInterestLabel__c, FollowUpProfileLabel__c,
                FollowUpButton1BgColor__c, FollowUpButton1FontColor__c, FollowUpButton1Label__c,
                FollowUpButton2BgColor__c, FollowUpButton2FontColor__c, FollowUpButton2Label__c,
                FollowUpContactImageURL__c, FollowUpContactTwitterHandle__c,
                Password__c, Username__c, LoginBodyColor__c,
                Page_1_Active__c, Page_2_Active__c, Page_3_Active__c, Page_4_Active__c, 
                Page_5_Active__c, Page_6_Active__c, Page_7_Active__c, Page_8_Active__c, 
                ChatterId__c, ChatterPositionX__c, ChatterPositionY__c,
                DashboardId__c, DashboardPositionX__c, DashboardPositionY__c,
                VisualforcePageName__c, VisualforcePageLocationX__c, VisualforcePageLocationY__c,
                AccountNumber__c, AccountType__c, AccountIndustry__c, AccountRating__c, 
                AccountPhone__c, AccountAddress__c, AccountDescription__c,
                AccountPersonName__c, AccountPersonBirthdate__c, AccountPersonEmail__c, IsTwoCol__c
                from iPadApplication__c where Active__c=true limit 1];

        if(appList!=null && appList.size()>0){
            iPadAppConfig = appList.get(0);
            if(iPadAppConfig.BodyIsUseImage__c){
                bgImage = iPadUtilClass.getBackgroundImage(iPadAppConfig.BodyBgImage__c, iPadAppConfig.BodyBgImageURL__c);
            }else{
                bgImage = 'none';
            }
            if(iPadAppConfig.LoginIsUseImage__c){
                loginImage = iPadUtilClass.getBackgroundImage(iPadAppConfig.LoginBgImage__c, iPadAppConfig.LoginBgImageURL__c);
            }else{
                loginImage = 'none';
            }
            if(String.isEmpty(iPadAppConfig.ChatterId__c)){
                iPadAppConfig.ChatterId__c = UserInfo.getUserId(); //show user feed by default
            }
            
            footerImageList = initFooterImageList();
        }    
    }

    private List<ApplicationImage__c> queryFooterImage(String pageType){
         return [select Id, Name, ImageURL__c, Label__c, FooterImageURL__c
            from ApplicationImage__c where iPadApplication__c=:iPadAppConfig.Id
            and IsFooterImage__c=true 
            and PageType__c=:pageType order by Name limit 1];    
    }

    public List<ApplicationImage__c> initFooterImageList(){
        List<ApplicationImage__c> imageList = new List<ApplicationImage__c>();
        if(iPadAppConfig.Page_1_Active__c){
            imageList = queryFooterImage(getPage1Name());
        }
        if(iPadAppConfig.Page_2_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage2Name())){
                imageList.add(image);
            }
        }
        if(iPadAppConfig.Page_3_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage3Name())){
                imageList.add(image);
            }
        }
        if(iPadAppConfig.Page_4_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage4Name())){
                imageList.add(image);
            }
        }
        if(iPadAppConfig.Page_5_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage5Name())){
                imageList.add(image);
            }
        }        
        if(iPadAppConfig.Page_6_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage6Name())){
                imageList.add(image);
            }
        }        
        if(iPadAppConfig.Page_7_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage7Name())){
                imageList.add(image);
            }
        }        
        if(iPadAppConfig.Page_8_Active__c){
            for(ApplicationImage__c image : queryFooterImage(getPage8Name())){
                imageList.add(image);
            }
        }        
        return imageList;
    }


}