objects/ApplicationFollowUpItem__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Activity Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckboxValue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checkbox Value</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IconURL__c</fullName>
        <label>Icon URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageType__c</fullName>
        <label>PageType</label>
        <picklist>
            <picklistValues>
                <fullName>Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SortNumber__c</fullName>
        <label>Sort Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TextValue__c</fullName>
        <label>Text Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Interest</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Profile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Activity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>iPadApplication__c</fullName>
        <label>iPad Application</label>
        <referenceTo>iPadApplication__c</referenceTo>
        <relationshipLabel>Application Follow Up Item</relationshipLabel>
        <relationshipName>Application_Follow_Up_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Follow Up Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Follow Up Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Follow Up Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ApplicationImage__c.object
<CustomObject>
    <fields>
        <fullName>ChartType__c</fullName>
        <label>Chart Type</label>
        <picklist>
            <picklistValues>
                <fullName>pie</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>column</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gauge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>funnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>scatter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>donut</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DasboardLegendLabel__c</fullName>
        <label>Dasboard Legend Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DasboardValueLabel__c</fullName>
        <label>Dasboard Value Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DashboardFromURL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dashboard From URL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DashboardURL__c</fullName>
        <label>Dashboard URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FooterImageURL__c</fullName>
        <formula>IF(IsFooterImage__c , 
    IF(ISPICKVAL( PageType__c , &apos;Page 1&apos;), &apos;#dPage3&apos;,
       IF(ISPICKVAL( PageType__c , &apos;Page 2&apos;), &apos;#dPage4&apos;,
          IF(ISPICKVAL( PageType__c , &apos;Page 3&apos;), &apos;#dPage5&apos;,
             IF(ISPICKVAL( PageType__c , &apos;Page 4&apos;), &apos;#dPage6&apos;,
                IF(ISPICKVAL( PageType__c , &apos;Page 5&apos;), &apos;#dPage7&apos;,
                   IF(ISPICKVAL( PageType__c , &apos;Page 6&apos;), &apos;#dPage8&apos;, &apos;&apos;
                   )
                )
             )
          )
       )
    )
, &apos;&apos;)</formula>
        <label>Footer Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Height__c</fullName>
        <label>Height (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ImageURL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsDashboardImage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dashboard Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsFooterImage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Footer Image</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LocationX__c</fullName>
        <defaultValue>0</defaultValue>
        <description>input location in px</description>
        <label>Location X (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LocationY__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Location in px</description>
        <label>Location Y (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PageType__c</fullName>
        <label>Page Type</label>
        <picklist>
            <picklistValues>
                <fullName>Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReportId__c</fullName>
        <label>Report Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <label>Width (px)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>iPadApplication__c</fullName>
        <label>iPad Application</label>
        <referenceTo>iPadApplication__c</referenceTo>
        <relationshipLabel>ApplicationImages</relationshipLabel>
        <relationshipName>ApplicationImages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Application Image</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Application Image Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApplicationImages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ApplicationLink__c.object
<CustomObject>
    <fields>
        <fullName>IsArticle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Article</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsVideo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PageType__c</fullName>
        <label>PageType</label>
        <picklist>
            <picklistValues>
                <fullName>Login Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landing Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Page 8</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>iPadApplication__c</fullName>
        <label>iPad Application</label>
        <referenceTo>iPadApplication__c</referenceTo>
        <relationshipLabel>Application Links</relationshipLabel>
        <relationshipName>ApplicationLinks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Link</label>
    <nameField>
        <label>Application Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/iPadApplication__c.object
<CustomObject>
    <label>iPad Application</label>
    <nameField>
        <label>iPad Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iPadApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IPadDemoComponentController.cls
public class IPadDemoComponentController{
    public Id applicationId{get; set;}
    public String username{get; set;}
    public String password{get; set;}
    public String bgImage {get; set;}
    public String currentComponent{get; set;}

    public Boolean accountIsPerson{get; set;}
    public Boolean accountPersonNameCtrl{get; set;}
    public Boolean accountNumberCtrl{get; set;}
    public Boolean accountTypeCtrl{get; set;}
    public Boolean accountIndustryCtrl{get; set;}
    public Boolean accountRatingCtrl{get; set;}
    public Boolean accountPhoneCtrl{get; set;}
    public Boolean accountAddressCtrl{get; set;}
    public Boolean accountDescriptionCtrl{get; set;}
    public Boolean accountBirthdateCtrl{get; set;}
    public Boolean accountEmailCtrl{get; set;}
    
    public Account account{ get; set;}
    public Contact contact{ get; set;}
    public Boolean page1Active{get; set;}
    public Boolean page2Active{get; set;}
    public Boolean page3Active{get; set;}
    public Boolean page4Active{get; set;}
    public Boolean page5Active{get; set;}
    public Boolean page6Active{get; set;}
    public Boolean page7Active{get; set;}
    public Boolean page8Active{get; set;}
    public String message{get; set;}
    public String chatterId{get; set;}

    public Boolean showEvents{get; set;}
    public Boolean showTasks{get; set;}
    public Date showDate{get; set;}

    public Account accountMap{get; set;}        
    public String chosenTaskAccountId{get; set;}    
    
    public IPadDemoComponentController(){
        account = new Account();
        contact = new Contact();
        chosenTaskAccountId = '';
        showDate= Date.today();
    }
    
    
    public void getChatterIdParam(){
        chatterId = ApexPages.currentPage().getParameters().get('id');
    }
    
    public PageReference saveAccount(){
        if(accountIsPerson){
            //account.RecordTypeId = [SELECT Id, Name, SobjectType, IsPersonType FROM RecordType WHERE SobjectType='Account' AND IsPersonType=True].Id;
            //System.debug('DEBUGGG recordTypeId: ' + account.RecordTypeId);
            /*account.Salutation = contact.salutation;
            account.firstname = contact.firstName;
            account.lastname = contact.lastName;
            account.PersonBirthdate = contact.birthdate;
            account.PersonEmail = contact.email;
            */
            account.Name = contact.salutation + ' ' + contact.firstName + ' ' + contact.lastName;
            insert contact;
        }
        insert account;

        message = 'Account Saved';
        return null;
    }


    public List<Account> getAccountList(){
        String queryString = 'select Name, ';
        if(accountNumberCtrl){
            queryString += 'accountNumber, ';            
        }
        if(accountTypeCtrl){
            queryString += 'type, ';            
        }
        if(accountIndustryCtrl){
            queryString += 'industry, ';            
        }
        if(accountRatingCtrl){
            queryString += 'rating, ';            
        }
        if(accountPhoneCtrl){
            queryString += 'phone, ';            
        }
        if(accountDescriptionCtrl){
            queryString += 'description, ';            
        }
        if(accountAddressCtrl){
            queryString += 'billingStreet, billingCity, billingState, billingCountry, ';
        }
        //remove last comma
        queryString = queryString.substring(0, queryString.length()-2);
        queryString += ' from Account order by LastModifiedDate desc';
        System.debug('DEBUGGG: '+queryString);
        return Database.query(queryString);
    }

    public List<ApplicationLink__c > getVideoList(){
        return [select Id, Name, IsArticle__c, IsVideo__c, PageType__c, URL__c 
            from ApplicationLink__c where iPadApplication__c=:applicationId
            and PageType__c=:currentComponent and IsVideo__c=true order by Name];
    }

    public List<ApplicationLink__c > getArticleList(){
        return [select Id, Name, IsArticle__c, IsVideo__c, PageType__c, URL__c 
            from ApplicationLink__c where iPadApplication__c=:applicationId
            and PageType__c=:currentComponent and IsArticle__c=true order by Name];
    }

    public List<ApplicationFollowUpItem__c> getFollowUpActivityItem(){
        return [select ActivityDate__c, IconURL__c, Label__c
             from ApplicationFollowUpItem__c where iPadApplication__c=:applicationId
             and PageType__c=:currentComponent and Type__c=:iPadUtilClass.getFollowUpTypeActivity()
             order by SortNumber__c, Name];
    }

    public List<ApplicationFollowUpItem__c> getFollowUpInterestItem(){
            return [select Id, CheckboxValue__c, Label__c
                from ApplicationFollowUpItem__c where iPadApplication__c=:applicationId
                and PageType__c=:currentComponent and Type__c=:iPadUtilClass.getFollowUpTypeInterest()
                order by SortNumber__c, Name];
    }

    public List<ApplicationFollowUpItem__c> getFollowUpProfileItem(){
            return [select Id, IconURL__c, Label__c, TextValue__c
             from ApplicationFollowUpItem__c where iPadApplication__c=:applicationId
             and PageType__c=:currentComponent and Type__c=:iPadUtilClass.getFollowUpTypeProfile()
             order by SortNumber__c, Name];
    }

    public List<ApplicationImage__c> getLogoList(){
        return [select ImageURL__c from ApplicationImage__c where iPadApplication__c=:applicationId
            and PageType__c=:iPadUtilClass.getLoginPageName() and IsFooterImage__c=false and IsDashboardImage__c=false order by Name];
    }

    public List<ApplicationImage__c> getImageList(){
        return [select Id, Name, Height__c, ImageURL__c, LocationX__c, LocationY__c, Width__c, PageType__c 
            from ApplicationImage__c where iPadApplication__c=:applicationId
            and PageType__c=:currentComponent and IsFooterImage__c=false and IsDashboardImage__c=false order by Name];
    }

    private List<ApplicationImage__c> queryFooterImage(String pageType){
         return [select Id, Name, ImageURL__c, PageType__c, Label__c, FooterImageURL__c
            from ApplicationImage__c where iPadApplication__c=:applicationId
            and IsFooterImage__c=true 
            and PageType__c=:pageType order by Name limit 1];    
    }

    public List<ApplicationImage__c> getDashboardImageList(){
        List<ApplicationImage__c> dashboardList = new List<ApplicationImage__c>();
        for (ApplicationImage__c appImage : [select Id, Name, Height__c, DashboardURL__c, Width__c, PageType__c, Label__c,
            DashboardFromURL__c, ChartType__c, ReportId__c, DasboardValueLabel__c, DasboardLegendLabel__c
            from ApplicationImage__c where iPadApplication__c=:applicationId
            and PageType__c=:currentComponent and IsDashboardImage__c=true order by Name]){
                if(!appImage.DashboardFromURL__c){    //create url string
                    appImage.DashboardURL__c = iPadUtilClass.getReportChartURL(appImage.ReportId__c, appImage.ChartType__c,
                        appImage.DasboardLegendLabel__c, appImage.DasboardValueLabel__c);
                }
                dashboardList.add(appImage);
            }
        return dashboardList;
    }

    public List<ApplicationImage__c> getMenuList(){
        List<ApplicationImage__c> imageList = new List<ApplicationImage__c>();
        if(page1Active){
            imageList = queryFooterImage(iPadUtilClass.getPage1Name());
        }
        if(page2Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage2Name())){
                imageList.add(image);
            }
        }        
        if(page3Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage3Name())){
                imageList.add(image);
            }
        }
        if(page4Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage4Name())){
                imageList.add(image);
            }
        }    
        if(page5Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage5Name())){
                imageList.add(image);
            }
        }
        if(page6Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage6Name())){
                imageList.add(image);
            }
        }
        if(page7Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage7Name())){
                imageList.add(image);
            }
        }
        if(page8Active){
            for(ApplicationImage__c image : queryFooterImage(iPadUtilClass.getPage8Name())){
                imageList.add(image);
            }
        }
        return imageList;
    }
    
    public Account queryAccountInfo(){
        return [select Name, Id, Phone, BillingPostalCode, BillingStreet, BillingCity, BillingState, BillingCountry from Account where id=:chosenTaskAccountId];
    }
    
    public PageReference refreshAccountMap(){
        accountMap = queryAccountInfo();
        return null;
    }

    public PageReference getPreviousMonth(){
        showDate = showDate.addMonths(-1);
        return null;
    }
    public PageReference getNextMonth(){
        showDate = showDate.addMonths(1);
        return null;
    }

    public CalendarMonthContainer getCalendarMonth(){ 
        return new CalendarMonthContainer(showDate.toStartOfMonth());
    }

    public List<TaskDateList> getTaskDateList(){
        List<TaskDateList> taskDateList = new List<TaskDateList>();
        if(showTasks!=null && showEvents!=null){
            List<Date> activityDateList = new List<Date>();
            for(AggregateResult ar : [select ActivityDate from Task where //OwnerId=:UserInfo.getUserId() and
                ActivityDate>=TODAY group by ActivityDate order by ActivityDate limit 5 ]){
                activityDateList.add((Date)ar.get('ActivityDate'));
            }
            for(AggregateResult ar : [select ActivityDate from Event where //OwnerId=:UserInfo.getUserId() and
                ActivityDate>=TODAY group by ActivityDate order by ActivityDate limit 5 ]){
                activityDateList.add((Date)ar.get('ActivityDate'));
            }
            activityDateList.sort();
            Date prevDate = Date.today().addDays(-1);
            for(Date dateItem : activityDateList){
                if(dateItem!=prevDate){
                    TaskDateList tdl = new TaskDateList(dateItem, showTasks, showEvents);
                    if((tdl.taskList!=null && tdl.taskList.size()>0) || (tdl.eventList!=null && tdl.eventList.size()>0)){
                        taskDateList.add(tdl);
                    }
                    prevDate = dateItem;
                }
            }
        }
        return taskDateList;
    }

    public class TaskDateList{
        public String activityDate {get; set;}
        public List<Task> taskList{get; set;}
        public List<Event> eventList{get; set;}

        public TaskDateList(Date d, Boolean bTask, Boolean bEvent){
            activityDate = d.format();
            taskList = new List<Task>();
            eventList = new List<Event>();
            if(bTask){
                taskList = queryTask(d);            
            }
            if(bEvent){
                eventList = queryEvent(d);            
            }
        }
        
        private List<Task> queryTask(Date d){
            return [select AccountId, ActivityDate, Description, Subject from Task 
            where //OwnerId=:UserInfo.getUserId() and 
            ActivityDate=:d
            order by ActivityDate desc];
        }

        private List<Event> queryEvent(Date d){
            return [select AccountId, ActivityDate, Description, Subject, StartDateTime, IsAllDayEvent from Event
            where //OwnerId=:UserInfo.getUserId() and 
            ActivityDate=:d
            order by ActivityDate desc];
        }
    }
    
    public class CalendarMonthContainer{
        public String month {get; set;}
        public List<CalendarWeekContainer> weekList {get;set;}
        public CalendarMonthContainer(Date startDate){
            this.month = iPadUtilClass.getMonthFromNumber(startDate.month());
            weekList = new List<CalendarWeekContainer>();

            Integer nDays = 7;
            Date tempDate = startDate;
            do{
                weekList.add(new CalendarWeekContainer(tempDate));
                tempDate = tempDate.addDays(nDays);
            }while(tempDate.month()==startDate.month());
            //last week
            if(tempDate.toStartOfWeek().month()==startDate.month()){
                weekList.add(new CalendarWeekContainer(tempDate));            
            }

        }    
    }
    public class CalendarWeekContainer{
        public List<String> dayList{get; set;}
        public CalendarWeekContainer(Date startDate){
            dayList = new List<String>();
            Date startWeekDate = startDate.toStartOfWeek(); 
            for(Integer i=0; i<7; i++){
                if(startDate.month()==startWeekDate.addDays(i).month()){
                    dayList.add(String.valueOf(startWeekDate.addDays(i).day()));
                }else{
                    dayList.add('');
                }

            }
        }
    }

}